# Generated by Django 2.2.1 on 2019-06-14 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=100, null=True, verbose_name='Фамилия')),
                ('third_name', models.CharField(max_length=100, null=True, verbose_name='Отчество')),
                ('users', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personshop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
            },
        ),
    ]
