# Generated by Django 2.2.1 on 2019-06-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_person_shine'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='brand',
            field=models.CharField(max_length=100, null=True, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='person',
            name='god',
            field=models.CharField(max_length=100, null=True, verbose_name='Год выпуска'),
        ),
        migrations.AddField(
            model_name='person',
            name='iznos1',
            field=models.CharField(max_length=100, null=True, verbose_name='Износ 1'),
        ),
        migrations.AddField(
            model_name='person',
            name='iznos2',
            field=models.CharField(max_length=100, null=True, verbose_name='Износ 2'),
        ),
        migrations.AddField(
            model_name='person',
            name='iznos3',
            field=models.CharField(max_length=100, null=True, verbose_name='Износ 3'),
        ),
        migrations.AddField(
            model_name='person',
            name='iznos4',
            field=models.CharField(max_length=100, null=True, verbose_name='Износ 4'),
        ),
        migrations.AddField(
            model_name='person',
            name='latki',
            field=models.CharField(max_length=100, null=True, verbose_name='Есть ли латки'),
        ),
        migrations.AddField(
            model_name='person',
            name='model',
            field=models.CharField(max_length=100, null=True, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='person',
            name='profile',
            field=models.CharField(max_length=100, null=True, verbose_name='Профиль'),
        ),
        migrations.AddField(
            model_name='person',
            name='radius',
            field=models.CharField(max_length=100, null=True, verbose_name='Радиус'),
        ),
        migrations.AddField(
            model_name='person',
            name='shirina',
            field=models.CharField(max_length=100, null=True, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='person',
            name='soglas',
            field=models.CharField(max_length=100, null=True, verbose_name='Согласен ли клиент'),
        ),
    ]
