# Generated by Django 2.2.1 on 2019-06-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190615_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cena',
            field=models.CharField(max_length=100, null=True, verbose_name='Общая цена'),
        ),
        migrations.AddField(
            model_name='person',
            name='iznos',
            field=models.CharField(max_length=100, null=True, verbose_name='Общий износ'),
        ),
        migrations.AddField(
            model_name='person',
            name='skidka',
            field=models.CharField(max_length=100, null=True, verbose_name='Скидка'),
        ),
    ]
