# Generated by Django 2.2.1 on 2019-06-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190615_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='person',
        ),
        migrations.AddField(
            model_name='company',
            name='person',
            field=models.ManyToManyField(to='login.Person'),
        ),
    ]
