# Generated by Django 2.2.1 on 2019-06-15 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0006_auto_20190615_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='users',
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personshop', to=settings.AUTH_USER_MODEL),
        ),
    ]
